# Generated by Django 4.0.5 on 2022-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadEX',
            fields=[
                ('date', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('number_session', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UploadGym',
            fields=[
                ('date', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('squat', models.CharField(max_length=4)),
                ('crunch', models.CharField(max_length=4)),
                ('yoga', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UploadYoga',
            fields=[
                ('date', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('number_session', models.CharField(max_length=4)),
            ],
        ),
    ]
